name: plugins_prod
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      SSL_DOMAIN: ${SSL_DOMAIN}
    command: >
      /bin/sh -c "envsubst '$$SSL_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - cache:/cache
      - zips:/zip
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
  web:
    image: ghcr.io/zsteinkamp/plugins:latest
    environment:
      GH_TOKEN: ${GH_TOKEN}
    ports:
      - 3000
    restart: always
    volumes:
      - cache:/cache
      - zips:/zip
volumes:
  cache:
  zips:
