name: plugins_prod
services:
  web:
    build:
      context: .
      target: prod
    ports:
      - '3225:3000'
    restart: unless-stopped
    volumes:
      - cache:/cache
      - zips:/zip
volumes:
  app_node_modules:
  cache:
  zips:
