name: plugins_prod
services:
  nginx:
    image: nginx:latest
    ports:
      - '3225:3225'
    volumes:
      - cache:/cache
      - ./nginx.conf:/etc/nginx/nginx.conf
  web:
    build:
      context: .
      target: prod
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - cache:/cache
      - zips:/zip
volumes:
  app_node_modules:
  cache:
  zips:
