name: plugins_dev
services:
  web:
    build:
      context: ..
      target: dev
    ports:
      - '3200:3000'
    volumes:
      - dev_cache:/cache
      - dev_zip:/zip
      - ..:/app
      - dev_node_modules:/app/node_modules
volumes:
  dev_cache: 
  dev_zip: 
  dev_node_modules:
