name: plugins_dev
services:
  web:
    build:
      context: ..
      target: dev
    ports:
      - '3200:3000'
    volumes:
      - cache:/cache
      - ..:/app
      - app_node_modules:/app/node_modules
volumes:
  app_node_modules:
  cache:
